### PR TITLE
feat(search): new page for searching items

### LINKED ISSUE #38: Suggestion: Search with Elastic Search and sharable links
Today i missed the Search functionality using the project. 

I suggest the implementation of search and REST search with Elastic Search and sharable links. 

Thanks!

### PR DESCRIPTION
**Pull request by nikosanif**
#### Description:
Create new page for searching songs, artists, albums, and playlists with Spotify API.

#### Referenced Issues:
- Resolves #38 

#### Changelog:
- Added new lib `web-search-feature` for search page
- Added new lib `web-search-data-access` for search store
- Added new lib `web-shared-ui-input` for UI input component
- Added new service which calls search endpoint of Spotify API
- Added new icon: `search`
- Changed `album-track` component to accept optionally custom track index
- Changed `media-cover` component to render rounded image

### CODE REVIEW

**Comment by trungk18** [comment]
@nikosanif That's awesome. Somehow I miss your PR, Nikos. I'll do a review tomorrow and probably we can merge it very soon. Thanks for your help 😆

**Review by trungk18 — APPROVED** [review]
Work great locally, I'll merge it first and might make some changes before publishing. Thanks @nikosanif for your contribution.

**Comment by nikosanif** [comment]
Great news @trungk18! 🥳
I am more than happy to hear that!

I was wondering if you can open more issues/features that you might have in mind for more future contributions.

**Comment by trungk18** [comment]
@nikosanif Sure, I'll add more issues to the list but at the moment I didn't have much. I started the lyrics integration with musixmatch but forgot to push it further 🤣

**Pull request merged**
