### PR TITLE
PWA installable App

### LINKED ISSUE #34: Suggestion: PWA installable App and Offline Frontend
Thinking in educational purpose of the App.
I suggest the PWA architecture implementation.

For make the application works offline(Don't playing song, but accessible). 
This approach can explore concepts with Connection Detection, Service Worker, Local Storage, Cache.

I'm anxious to see that in a Live on Youtube!

Thanks!

### PR DESCRIPTION
**Pull request by nikosanif**
#### Referenced Issues:
- Resolves #34 

#### Changelog:
- Install @angular/pwa
- Register service worker
- Update `index.prod.html` with meta tag and theme colour
- Add custom icons for PWA

### CODE REVIEW

**Comment by nikosanif** [comment]
Hi @trungk18, I made a pull request for this issue since it was tagged as `help-wanted`. I'll be happy if you can review and merge it.

**Comment by trungk18** [comment]
Thanks @nikosanif, I'll look into it shortly 😁
@nartc Bro, would you please help to also look into it quickly?

**Comment by nikosanif** [comment]
Here are some screenshots from the installation:

Screenshot 2021-04-13 at 11 18 19 AM
Screenshot 2021-04-13 at 11 20 21 AM

**Comment by trungk18** [comment]
@nikosanif For some reasons, I didn't see it working locally for the production build on your branch. Do you have a better idea on that? 

Screenshot 2021-04-19 at 9 14 22 PM

**Comment by nikosanif** [comment]
Hi @trungk18 , I did the following steps:
- Build app in production
    ```sh
    $ npm run build:prod
    ```
- Install [http-server](https://www.npmjs.com/package/http-server) package globally
    ```sh
    $ npm i -g http-server
    ```
- Serve built files
    ```sh
    $ cd dist/apps/angular-spotify/
    $ http-server -p 4200 -o
    ```
- Open your browser at `http://localhost:4200/`, wait a few seconds and this icon will appear:
    

Don’t hesitate to contact me if you have any issues.

**Comment by trungk18** [comment]
@nikosanif Thank you so much, it works perfectly awesome 🌟

https://user-images.githubusercontent.com/6767322/115731387-ad7f2400-a3b9-11eb-87e9-78dcd9c75ea9.mp4

**Pull request merged**
